-
  - 'Chitra Sachdeva'
  - 'Head Coach'
  - 'The Aw35ome Batch'
-
  - 'Shalini Anand'
  - 'Defensive Coordinator'
  - 'The Aw35ome Batch'
-
  - 'Bill Schofield'
  - 'Learning Coach'
  - 'Junior Consultants'
-
  - 'Pat Sarnacke'
  - 'Head Coach'
  - 'Junior Consultants'
-
  - 'Joanna Parke'
  - 'Head Coach'
  - 'Laterals'
-
  - 'Julian Oliver'
  - 'Offensive Coordinator'
  - 'Laterals'
-
  - 'Jason Pfetcher'
  - 'Head Coach'
  - 'Legal and Immigration'
-
  - 'Jami Best'
  - 'Head Coach'
  - 'People Support'
-
  - 'Roy Singham'
  - 'Some Guy'
  - 'People Support'
-
  - 'Ace McDonough'
  - 'Head Coach'
  - 'TechOps'
-
  - 'Yewande Ige'
  - 'Head Coach'
  - 'Recruiting'
-
  - 'Tess Zelechowski'
  - 'JC Coordinator'
  - 'Recruiting'
